-- MySQL Script generated by MySQL Workbench
-- 03/21/17 15:24:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hackqc17
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `gtfs_agency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_agency` ;

CREATE TABLE IF NOT EXISTS `gtfs_agency` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `agency_id` VARCHAR(255) NULL,
  `agency_name` VARCHAR(255) NULL,
  `agency_url` VARCHAR(255) NULL,
  `agency_timezone` VARCHAR(255) NULL,
  `agency_lang` VARCHAR(45) NULL,
  `agency_phone` VARCHAR(45) NULL,
  `agency_fare_url` VARCHAR(255) NULL,
  `agency_email` VARCHAR(255) NULL,
  `lng_min` DOUBLE NULL,
  `lng_max` DOUBLE NULL,
  `lat_min` DOUBLE NULL,
  `lat_max` DOUBLE NULL,
  PRIMARY KEY (`pk`),
  INDEX `index3` (`agency_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_zone` ;

CREATE TABLE IF NOT EXISTS `gtfs_zone` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `lon_topleft` DOUBLE NULL,
  `lat_topleft` DOUBLE NULL,
  `lon_botright` DOUBLE NULL,
  `lat_botright` DOUBLE NULL,
  `resolution` INT NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_stop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_stop` ;

CREATE TABLE IF NOT EXISTS `gtfs_stop` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `stop_id` VARCHAR(255) NULL,
  `stop_code` VARCHAR(255) NULL,
  `stop_name` VARCHAR(255) NULL,
  `stop_lat` DOUBLE NULL,
  `stop_lon` DOUBLE NULL,
  `stop_desc` VARCHAR(45) NULL,
  `parent_station` VARCHAR(255) NULL,
  `agency_pk` INT NOT NULL,
  `gtfs_zone_pk` INT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_stop_agency1_idx` (`agency_pk` ASC),
  INDEX `fk_gtfs_stop_gtfs_zone1_idx` (`gtfs_zone_pk` ASC),
  CONSTRAINT `fk_gtfs_stop_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_stop_gtfs_zone1`
    FOREIGN KEY (`gtfs_zone_pk`)
    REFERENCES `gtfs_zone` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_route` ;

CREATE TABLE IF NOT EXISTS `gtfs_route` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `route_id` VARCHAR(255) NULL,
  `agency_pk` INT NOT NULL,
  `route_short_name` VARCHAR(255) NULL,
  `route_long_name` VARCHAR(255) NULL,
  `route_desc` TEXT NULL,
  `route_type` INT NOT NULL,
  `route_url` VARCHAR(255) NULL,
  `route_color` VARCHAR(45) NULL,
  `route_text_color` VARCHAR(45) NULL,
  `zone_pk` INT NULL,
  `agency_id` VARCHAR(255) NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_routes_gtfs_agency1_idx` (`agency_pk` ASC),
  INDEX `fk_gtfs_route_gtfs_zone1_idx` (`zone_pk` ASC),
  CONSTRAINT `fk_gtfs_routes_gtfs_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_route_gtfs_zone1`
    FOREIGN KEY (`zone_pk`)
    REFERENCES `gtfs_zone` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_calendar` ;

CREATE TABLE IF NOT EXISTS `gtfs_calendar` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `service_id` VARCHAR(45) NOT NULL,
  `monday` INT NULL,
  `tuesday` INT NULL,
  `wednesday` INT NULL,
  `thursday` INT NULL,
  `friday` INT NULL,
  `saturday` INT NULL,
  `sunday` INT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `agency_pk` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_calendar_gtfs_agency1_idx` (`agency_pk` ASC),
  INDEX `index3` (`service_id` ASC),
  CONSTRAINT `fk_gtfs_calendar_gtfs_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_calendar_dates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_calendar_dates` ;

CREATE TABLE IF NOT EXISTS `gtfs_calendar_dates` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `service_id` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  `exception_type` INT NULL,
  `agency_pk` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_calendar_dates_gtfs_agency1_idx` (`agency_pk` ASC),
  INDEX `index3` (`service_id` ASC),
  CONSTRAINT `fk_gtfs_calendar_dates_gtfs_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_shape`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_shape` ;

CREATE TABLE IF NOT EXISTS `gtfs_shape` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `shape_id` VARCHAR(255) NULL,
  `agency_pk` INT NOT NULL,
  `route_pk` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_shapes_gtfs_agency1_idx` (`agency_pk` ASC),
  INDEX `fk_gtfs_shape_gtfs_route1_idx` (`route_pk` ASC),
  CONSTRAINT `fk_gtfs_shapes_gtfs_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_shape_gtfs_route1`
    FOREIGN KEY (`route_pk`)
    REFERENCES `gtfs_route` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_trip` ;

CREATE TABLE IF NOT EXISTS `gtfs_trip` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `trip_id` VARCHAR(255) NULL,
  `route_pk` INT NOT NULL,
  `agency_pk` INT NOT NULL,
  `shape_pk` INT NULL,
  `trip_headsign` VARCHAR(255) NULL,
  `block_id` VARCHAR(255) NULL,
  `trip_short_name` VARCHAR(255) NULL,
  `direction_id` VARCHAR(255) NULL,
  `departure_time` TIME NULL,
  `arrival_time` TIME NULL,
  `departure_sec` INT NULL,
  `arrival_sec` INT NULL,
  `service_id` VARCHAR(255) NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_trips_gtfs_routes1_idx` (`route_pk` ASC),
  INDEX `fk_gtfs_trips_gtfs_agency1_idx` (`agency_pk` ASC),
  INDEX `fk_gtfs_trips_gtfs_shapes1_idx` (`shape_pk` ASC),
  CONSTRAINT `fk_gtfs_trips_gtfs_routes1`
    FOREIGN KEY (`route_pk`)
    REFERENCES `gtfs_route` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_trips_gtfs_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_trips_gtfs_shapes1`
    FOREIGN KEY (`shape_pk`)
    REFERENCES `gtfs_shape` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_stop_times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_stop_times` ;

CREATE TABLE IF NOT EXISTS `gtfs_stop_times` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `trip_pk` INT NOT NULL,
  `arrival_time` TIME NULL,
  `departure_time` TIME NULL,
  `stop_pk` INT NOT NULL,
  `stop_sequence` INT NULL,
  `stop_headsign` VARCHAR(255) NULL,
  `pickup_type` VARCHAR(45) NULL,
  `drop_off_type` VARCHAR(45) NULL,
  `shape_dist_traveled` DOUBLE NULL,
  `arrival_sec` INT NULL,
  `departure_sec` INT NULL,
  `agency_pk` INT NOT NULL,
  INDEX `fk_gtfs_stop_times_gtfs_trip1_idx` (`trip_pk` ASC),
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_stop_times_gtfs_stop1_idx` (`stop_pk` ASC),
  INDEX `fk_gtfs_stop_times_gtfs_agency1_idx` (`agency_pk` ASC),
  CONSTRAINT `fk_gtfs_stop_times_gtfs_trip1`
    FOREIGN KEY (`trip_pk`)
    REFERENCES `gtfs_trip` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_stop_times_gtfs_stop1`
    FOREIGN KEY (`stop_pk`)
    REFERENCES `gtfs_stop` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_stop_times_gtfs_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_frequency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_frequency` ;

CREATE TABLE IF NOT EXISTS `gtfs_frequency` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `gtfs_trip_pk` INT NOT NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `headway_secs` INT NULL,
  INDEX `fk_gtfs_frequency_gtfs_trip1_idx` (`gtfs_trip_pk` ASC),
  PRIMARY KEY (`pk`),
  CONSTRAINT `fk_gtfs_frequency_gtfs_trip1`
    FOREIGN KEY (`gtfs_trip_pk`)
    REFERENCES `gtfs_trip` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtfs_shape_stops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gtfs_shape_stops` ;

CREATE TABLE IF NOT EXISTS `gtfs_shape_stops` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `shape_pk` INT NOT NULL,
  `stop_pk` INT NULL,
  `shape_pt_lat` DOUBLE NULL,
  `shape_pt_lon` DOUBLE NULL,
  `shape_pt_sequence` INT NULL,
  `shape_dist_traveled` DOUBLE NULL,
  `agency_pk` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_gtfs_shape_gtfs_stop1_idx` (`stop_pk` ASC),
  INDEX `fk_gtfs_shape_stops_gtfs_shape1_idx` (`shape_pk` ASC),
  INDEX `fk_gtfs_shape_stops_gtfs_agency1_idx` (`agency_pk` ASC),
  CONSTRAINT `fk_gtfs_shape_gtfs_stop10`
    FOREIGN KEY (`stop_pk`)
    REFERENCES `gtfs_stop` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_shape_stops_gtfs_shape1`
    FOREIGN KEY (`shape_pk`)
    REFERENCES `gtfs_shape` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gtfs_shape_stops_gtfs_agency1`
    FOREIGN KEY (`agency_pk`)
    REFERENCES `gtfs_agency` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bixi_od`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bixi_od` ;

CREATE TABLE IF NOT EXISTS `bixi_od` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `start_stop` VARCHAR(45) NULL,
  `start_date` DATETIME NULL,
  `end_stop` VARCHAR(45) NULL,
  `end_date` DATETIME NULL,
  `duration` INT NULL,
  `is_member` TINYINT(1) NULL,
  `gender` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
